// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"type/controllers"
	"type/dao"
	"type/routes"
	"type/service"
)

// Injectors from wire.go:

func InitApp() App {
	scoreDAOInterface := dao.NewScoreDAO()
	scoreServiceInterface := service.NewScoreService(scoreDAOInterface)
	scoreController := controllers.NewScoreController(scoreServiceInterface)
	userDAOInterface := dao.NewUserDAO()
	userServiceInterface := service.NewUserService(userDAOInterface)
	userController := controllers.NewUserController(userServiceInterface)
	songDAOInterface := dao.NewSongDAO()
	songServiceInterface := service.NewSongService(songDAOInterface)
	songController := controllers.NewSongController(songServiceInterface)
	assetDAOInterface := dao.NewAssetDAO()
	assetServiceInterface := service.NewAssetService(assetDAOInterface)
	assetController := controllers.NewAssetController(assetServiceInterface)
	engine := routes.RegisterRoutes(scoreController, userController, songController, assetController)
	app := NewApp(engine)
	return app
}
