// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package routes

import (
	"type/controllers"
	"type/dao"
	"type/service"
)

// Injectors from wire.go:

func InitSongController() *controllers.SongController {
	songDAOInterface := dao.NewSongDAO()
	songServiceInterface := service.NewSongService(songDAOInterface)
	songController := controllers.NewSongController(songServiceInterface)
	return songController
}

func InitScoreController() *controllers.ScoreController {
	scoreDAOInterface := dao.NewScoreDAO()
	scoreServiceInterface := service.NewScoreService(scoreDAOInterface)
	scoreController := controllers.NewScoreController(scoreServiceInterface)
	return scoreController
}

func InitUserController() *controllers.UserController {
	userDAOInterface := dao.NewUserDAO()
	userServiceInterface := service.NewUserService(userDAOInterface)
	userController := controllers.NewUserController(userServiceInterface)
	return userController
}

func InitAssetController() *controllers.AssetController {
	assetDAOInterface := dao.NewAssetDAO()
	assetServiceInterface := service.NewAssetService(assetDAOInterface)
	assetController := controllers.NewAssetController(assetServiceInterface)
	return assetController
}
